// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKiaqMqfbIQDU01955JdYViVCyrNku3Qo',
    appId: '1:1093883717402:web:abb7af20c185cc6b19aea3',
    messagingSenderId: '1093883717402',
    projectId: 'setapcoursework',
    authDomain: 'setapcoursework.firebaseapp.com',
    storageBucket: 'setapcoursework.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10Ck0QDMYZlWDeNdLvHOAHuaZYI_5XYU',
    appId: '1:1093883717402:android:61f30b71af3f187a19aea3',
    messagingSenderId: '1093883717402',
    projectId: 'setapcoursework',
    storageBucket: 'setapcoursework.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr26FwE8TTkdhkgUXY9jgEdQTMATiE788',
    appId: '1:1093883717402:ios:196a90e39112350419aea3',
    messagingSenderId: '1093883717402',
    projectId: 'setapcoursework',
    storageBucket: 'setapcoursework.appspot.com',
    iosBundleId: 'com.example.setapprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr26FwE8TTkdhkgUXY9jgEdQTMATiE788',
    appId: '1:1093883717402:ios:196a90e39112350419aea3',
    messagingSenderId: '1093883717402',
    projectId: 'setapcoursework',
    storageBucket: 'setapcoursework.appspot.com',
    iosBundleId: 'com.example.setapprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKiaqMqfbIQDU01955JdYViVCyrNku3Qo',
    appId: '1:1093883717402:web:5dc903ed35e8f09f19aea3',
    messagingSenderId: '1093883717402',
    projectId: 'setapcoursework',
    authDomain: 'setapcoursework.firebaseapp.com',
    storageBucket: 'setapcoursework.appspot.com',
  );
}
